name: Build

on:
  workflow_dispatch:

jobs:
  build-rootless:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@main

      - name: Checkout RootHide/theos
        uses: actions/checkout@main
        with:
          repository: RootHide/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout SDKs
        uses: actions/checkout@main
        with:
          repository: xybp888/iOS-SDKs
          ref: master
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks

      - name: Install dependencies
        run: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install make xz ldid

      - name: Build package (rootless)
        run: THEOS=theos gmake clean package TARGET="iphone:clang:16.2:13.0" FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Build package (roothide)
        run: THEOS=theos gmake clean package TARGET="iphone:clang:16.2:13.0" FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Build package (rootful)
        run: THEOS=theos gmake clean package TARGET="iphone:clang:16.2:13.0" FINALPACKAGE=1


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/*.deb

